// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikogbedmigsgcgheusrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlrb2diZWRtaWdzZ2NnaGV1c3JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MTc1NTksImV4cCI6MjA3Njk5MzU1OX0.5CYJ2ZP1UHJyS9tFDSoWd60fSY3y3QdE8nMW7U6CFm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});